name = "pb"
compatibility_date = "2023-01-28"
compatibility_flags = [ "nodejs_compat" ]

workers_dev = false
main = "src/index.js"

rules = [
  { type = "Text", globs = [ "*/frontend/**", "*/doc/**" ], fallthrough = true }
]

#----------------------------------------
# lines below are what you should modify
#----------------------------------------

[[routes]]
# Refer to https://developers.cloudflare.com/workers/wrangler/configuration/#routes
pattern = "pastebin.m78.dev"
custom_domain = true

[[kv_namespaces]]
binding = "PB"  # do not touch this
id = "04caa701dfe9451e92022efc91636b90"  # id of your KV namespace

[vars]
# must be consistent with your routes
BASE_URL = "https://pastebin.m78.dev"

# url to repo, displayed in index page
REPO = "https://github.com/SharzyL/pastebin-worker"

# url to favicon
FAVICON = "https://files.uhoo.cc/2f3e90f64d1797423201115f8fb1eae4_Pasta_1024x1024x32-5aSZOa.png"

# the name displayed in TOS
TOS_MAINTAINER = "M78 Pastebin"

# the email displayed in TOS
TOS_MAIL = ""

# Cache-Control max-age for static pages
CACHE_STATIC_PAGE_AGE = 7200

# Cache-Control max-age for static pages
CACHE_PASTE_AGE = 600
